### ISSUE TITLE
org-mode parser npm license to MIT or BSD?

### ISSUE THREAD

**Issue by xeijin** [daitangio/org-mode-parser#15]
Hello daitangio,

Firstly thank you for the superb library. I wanted to use for my own org-mode files within my company, but unfortunately the policy does not allow us to request software with GPL licenses from Node.

Would it be possible to **switch the npm version** to another acceptable license (e.g. FreeBSD, MIT) so that I am able to use at work? (We import packages directly from npm, so the license would need to be changed there if this is possible)

Many thanks!

**Comment by daitangio** [comment]
Hi, Okey I will change the license for better interop. Give me few days to decide. Do you have suggestion between BSD and MIT?

**Comment by xeijin** [comment]
No preference either is fine with me. Many thanks!

**Comment by daitangio** [comment]
I decided to change to MIT license, the same of nodejs and things like jQuery.
Please retain copyright attribution.
Also can you give me the name of the project will use the org mode parser (to track it)?

**Comment by xeijin** [comment]
@daitangio https://github.com/xeijin/propositum

Many thanks!

**Comment by xeijin** [comment]
@daitangio Would you also mind doing a release so that the updated license gets pushed to npm? (still shows GPL 2 on the NPM site)
